<a href="https://colab.research.google.com/github/alra-code/Portifolio_python/blob/main/An%C3%A1lise_de_dados_com_python_modulo_1_Tic_em_Trilhas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
cidades=["São Paulo(SP)","Manaus(AM)","Brasília(DF)" ]
cidades_serie=pd.Series(cidades)
print(cidades_serie)

0    São Paulo(SP)
1       Manaus(AM)
2     Brasília(DF)
dtype: object

In [6]:
cidades_serie[2]

'Brasília(DF)'

In [7]:
print(cidades_serie[:2])

0    São Paulo(SP)
1       Manaus(AM)
dtype: object

In [10]:
cidades_serie=pd.Series (["São Paulo(SP)",
                            "Manaus(AM)",
                            "Brasília(DF)"])

populacoes_serie=pd.Series ([12.0,
                              6.5,
                              3.0])

In [12]:
cidades_populosas=pd.DataFrame({"Cidade": cidades_serie,
                                   "População em milhões": populacoes_serie})
print(cidades_populosas)

          Cidade  População em milhões
0  São Paulo(SP)                  12.0
1     Manaus(AM)                   6.5
2   Brasília(DF)                   3.0

In [13]:
print(cidades_populosas["Cidade"])

0    São Paulo(SP)
1       Manaus(AM)
2     Brasília(DF)
Name: Cidade, dtype: object

In [14]:
print(cidades_populosas.iloc[:2])

          Cidade  População em milhões
0  São Paulo(SP)                  12.0
1     Manaus(AM)                   6.5

In [16]:
media_populacao=cidades_populosas["População em milhões"].mean()
print(media_populacao)
print("Média da população:",f'{media_populacao:.2f}',"milhões de habitantes")

7.166666666666667
Média da população: 7.17 milhões de habitantes

In [18]:
area_urbana=['914','640','590']
cidades_populosas['Área Urbana (km²)']=area_urbana
print(cidades_populosas)

          Cidade  População em milhões Área Urbana (km²)
0  São Paulo(SP)                  12.0               914
1     Manaus(AM)                   6.5               640
2   Brasília(DF)                   3.0               590

In [20]:
valor_bruto=cidades_populosas['População em milhões']*1_000_000
cidades_populosas['População - Valor Bruto']=valor_bruto
print(cidades_populosas)
cidades_populosas

          Cidade  População em milhões Área Urbana (km²)  \
0  São Paulo(SP)                  12.0               914
1     Manaus(AM)                   6.5               640
2   Brasília(DF)                   3.0               590

   População - Valor Bruto
0               12000000.0
1                6500000.0
2                3000000.0

,Cidade,População em milhões,Área Urbana (km²),População - Valor Bruto
0,São Paulo(SP),12.0,914,12000000.0
1,Manaus(AM),6.5,640,6500000.0
2,Brasília(DF),3.0,590,3000000.0

In [22]:
int_area_urbana=cidades_populosas['Área Urbana (km²)'].astype(int)
cidades_populosas['Área Urbana (km²)']=int_area_urbana
cidades_populosas

,Cidade,População em milhões,Área Urbana (km²),População - Valor Bruto
0,São Paulo(SP),12.0,914,12000000.0
1,Manaus(AM),6.5,640,6500000.0
2,Brasília(DF),3.0,590,3000000.0

In [24]:
habitantes_por_km2=cidades_populosas['População em milhões']/cidades_populosas['Área Urbana (km²)']
cidades_populosas['Habitantes por km²']=habitantes_por_km2
cidades_populosas

,Cidade,População em milhões,Área Urbana (km²),População - Valor Bruto,Habitantes por km²
0,São Paulo(SP),12.0,914,12000000.0,0.013129
1,Manaus(AM),6.5,640,6500000.0,0.010156
2,Brasília(DF),3.0,590,3000000.0,0.005085

from matplotlib import pyplot as plt
cidades_populosas['População em milhões'].plot(kind='hist', bins=20, title='População em milhões')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
cidades_populosas['Área Urbana (km²)'].plot(kind='hist', bins=20, title='Área Urbana (km²)')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
cidades_populosas['População - Valor Bruto'].plot(kind='hist', bins=20, title='População - Valor Bruto')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
cidades_populosas['Habitantes por km²'].plot(kind='hist', bins=20, title='Habitantes por km²')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
cidades_populosas.groupby('Cidade').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
cidades_populosas.plot(kind='scatter', x='População em milhões', y='Área Urbana (km²)', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
cidades_populosas.plot(kind='scatter', x='Área Urbana (km²)', y='População - Valor Bruto', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
cidades_populosas.plot(kind='scatter', x='População - Valor Bruto', y='Habitantes por km²', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
cidades_populosas['População em milhões'].plot(kind='line', figsize=(8, 4), title='População em milhões')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
cidades_populosas['Área Urbana (km²)'].plot(kind='line', figsize=(8, 4), title='Área Urbana (km²)')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
cidades_populosas['População - Valor Bruto'].plot(kind='line', figsize=(8, 4), title='População - Valor Bruto')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
cidades_populosas['Habitantes por km²'].plot(kind='line', figsize=(8, 4), title='Habitantes por km²')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(cidades_populosas['Cidade'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(cidades_populosas, x='População em milhões', y='Cidade', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(cidades_populosas['Cidade'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(cidades_populosas, x='Área Urbana (km²)', y='Cidade', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(cidades_populosas['Cidade'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(cidades_populosas, x='População - Valor Bruto', y='Cidade', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(cidades_populosas['Cidade'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(cidades_populosas, x='Habitantes por km²', y='Cidade', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)