<a href="https://colab.research.google.com/github/alra-code/Portifolio_python/blob/main/An%C3%A1lise_de_dados_com_python_modulo_2_Filtragem_Selecao_UniaoDeTabelas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Filtragem e Seleção de Dados com o Pandas

### Carregando dados

In [22]:
#importação da bilbioteca
import pandas as pd

#lendo o arquivo
df_populacao=pd.read_csv('/content/drive/MyDrive/CURSOS/Estudos - Data Analitycs/Tic - Análise de dados com paython /Módulo 2/Aula 2/populacao.csv')
print(type(df_populacao))

<class 'pandas.core.frame.DataFrame'>

In [19]:
df_populacao.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319 entries, 0 to 318
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ranking    319 non-null    int64
 1   municipio  319 non-null    object
 2   uf         319 non-null    object
 3   populacao  319 non-null    int64
dtypes: int64(2), object(2)
memory usage: 10.1+ KB

In [6]:
df_populacao.head() #5 primeiros dados

   ranking       municipio                uf  populacao
0        1       São Paulo         São Paulo   11451999
1        2  Rio de Janeiro    Rio de Janeiro    6211223
2        3        Brasília  Distrito Federal    2817381
3        4       Fortaleza             Ceará    2428708
4        5        Salvador             Bahia    2417678

In [23]:
df_populacao.tail() #5 ultimos dados

     ranking   municipio              uf  populacao
314      315  Manacapuru        Amazonas     101883
315      316      Balsas        Maranhão     101767
316      317     Lagarto         Sergipe     101579
317      318       Assis       São Paulo     101409
318      319   Itaperuna  Rio de Janeiro     101041

## Acessando as colunas

In [7]:
df_populacao["municipio"]

0           São Paulo
1      Rio de Janeiro
2            Brasília
3           Fortaleza
4            Salvador
            ...
314        Manacapuru
315            Balsas
316           Lagarto
317             Assis
318         Itaperuna
Name: municipio, Length: 319, dtype: object

In [8]:
df_populacao['uf']

0             São Paulo
1        Rio de Janeiro
2      Distrito Federal
3                 Ceará
4                 Bahia
             ...
314            Amazonas
315            Maranhão
316             Sergipe
317           São Paulo
318      Rio de Janeiro
Name: uf, Length: 319, dtype: object

In [25]:
df_populacao[['ranking','uf']]

     ranking                uf
0          1         São Paulo
1          2    Rio de Janeiro
2          3  Distrito Federal
3          4             Ceará
4          5             Bahia
..       ...               ...
314      315          Amazonas
315      316          Maranhão
316      317           Sergipe
317      318         São Paulo
318      319    Rio de Janeiro

[319 rows x 2 columns]

## Acessando valores específicos

In [10]:
df_populacao.iloc[9]

ranking           10
municipio    Goiânia
uf             Goiás
populacao    1437366
Name: 9, dtype: object

In [9]:
df_populacao.iloc[10:20]

    ranking     municipio                  uf  populacao
10       11  Porto Alegre   Rio Grande do Sul    1332845
11       12         Belém                Pará    1303403
12       13     Guarulhos           São Paulo    1291771
13       14      Campinas           São Paulo    1139047
14       15      São Luís            Maranhão    1037775
15       16        Maceió             Alagoas     957916
16       17  Campo Grande  Mato Grosso do Sul     898100
17       18   São Gonçalo      Rio de Janeiro     896744
18       19      Teresina               Piauí     866300
19       20   João Pessoa             Paraíba     833932

In [13]:
df_populacao[df_populacao['ranking'] == 10]

   ranking municipio     uf  populacao
9       10   Goiânia  Goiás    1437366

In [14]:
df_populacao[df_populacao['uf'] == 'Rio Grande do Sul']

     ranking          municipio                 uf  populacao
10        11       Porto Alegre  Rio Grande do Sul    1332845
47        48      Caxias do Sul  Rio Grande do Sul     463501
78        79             Canoas  Rio Grande do Sul     347657
85        86            Pelotas  Rio Grande do Sul     325685
102      103        Santa Maria  Rio Grande do Sul     271735
106      107           Gravataí  Rio Grande do Sul     265074
133      134      Novo Hamburgo  Rio Grande do Sul     227646
139      140             Viamão  Rio Grande do Sul     224112
143      144       São Leopoldo  Rio Grande do Sul     217409
146      147        Passo Fundo  Rio Grande do Sul     206215
157      158         Rio Grande  Rio Grande do Sul     191900
159      160           Alvorada  Rio Grande do Sul     187315
217      218       Cachoeirinha  Rio Grande do Sul     136258
223      224  Santa Cruz do Sul  Rio Grande do Sul     133230
225      226    Sapucaia do Sul  Rio Grande do Sul     132107
247      248    Bento Gonçalves  Rio Grande do Sul     123151
259      260               Bagé  Rio Grande do Sul     117938
261      262         Uruguaiana  Rio Grande do Sul     117210
294      295            Erechim  Rio Grande do Sul     105705

In [17]:
df_populacao[df_populacao['municipio'] == 'Poços de Caldas']

     ranking        municipio            uf  populacao
182      183  Poços de Caldas  Minas Gerais     163742

In [18]:
df_populacao[df_populacao['municipio'] == "Gramado"] # cidade com menos de 100k de habitantes, por isso não aparece

Empty DataFrame
Columns: [ranking, municipio, uf, populacao]
Index: []

## Combinando condições

In [31]:
df_populacao[(df_populacao['ranking'] > 10) & (df_populacao['ranking'] < 20 )]

    ranking     municipio                  uf  populacao
10       11  Porto Alegre   Rio Grande do Sul    1332845
11       12         Belém                Pará    1303403
12       13     Guarulhos           São Paulo    1291771
13       14      Campinas           São Paulo    1139047
14       15      São Luís            Maranhão    1037775
15       16        Maceió             Alagoas     957916
16       17  Campo Grande  Mato Grosso do Sul     898100
17       18   São Gonçalo      Rio de Janeiro     896744
18       19      Teresina               Piauí     866300

In [32]:
df_populacao[(df_populacao['ranking'] > 100) & (df_populacao['ranking'] < 120 )]

     ranking             municipio                   uf  populacao
100      101       Taboão da Serra            São Paulo     273542
101      102            Imperatriz             Maranhão     273110
102      103           Santa Maria    Rio Grande do Sul     271735
103      104              São José       Santa Catarina     270299
104      105           Parauapebas                 Pará     267836
105      106                Marabá                 Pará     266533
106      107              Gravataí    Rio Grande do Sul     265074
107      108               Mossoró  Rio Grande do Norte     264577
108      109                Itajaí       Santa Catarina     264054
109      110         Volta Redonda       Rio de Janeiro     261563
110      111  Governador Valadares         Minas Gerais     257171
111      112            Indaiatuba            São Paulo     255748
112      113            São Carlos            São Paulo     254857
113      114               Chapecó       Santa Catarina     254785
114      115            Parnamirim  Rio Grande do Norte     252716
115      116        Embu das Artes            São Paulo     250691
116      117                 Macaé       Rio de Janeiro     246391
117      118          Rondonópolis          Mato Grosso     244911
118      119   São José de Ribamar             Maranhão     244579

## Filtrando multiplos valores

In [35]:
regiao_sul= ['Rio Grande do Sul','Santa Catarina','Paraná']
df_populacao_sul=df_populacao[df_populacao['uf'].isin(regiao_sul)]
df_populacao_sul

     ranking             municipio                 uf  populacao
7          8              Curitiba             Paraná    1773718
10        11          Porto Alegre  Rio Grande do Sul    1332845
33        34             Joinville     Santa Catarina     616317
36        37              Londrina             Paraná     555965
38        39         Florianópolis     Santa Catarina     537211
47        48         Caxias do Sul  Rio Grande do Sul     463501
60        61               Maringá             Paraná     409657
70        71              Blumenau     Santa Catarina     361261
71        72          Ponta Grossa             Paraná     358371
77        78              Cascavel             Paraná     348051
78        79                Canoas  Rio Grande do Sul     347657
84        85  São José dos Pinhais             Paraná     329628
85        86               Pelotas  Rio Grande do Sul     325685
96        97         Foz do Iguaçu             Paraná     285415
102      103           Santa Maria  Rio Grande do Sul     271735
103      104              São José     Santa Catarina     270299
106      107              Gravataí  Rio Grande do Sul     265074
108      109                Itajaí     Santa Catarina     264054
113      114               Chapecó     Santa Catarina     254785
129      130               Colombo             Paraná     232212
133      134         Novo Hamburgo  Rio Grande do Sul     227646
139      140                Viamão  Rio Grande do Sul     224112
140      141               Palhoça     Santa Catarina     222598
143      144          São Leopoldo  Rio Grande do Sul     217409
144      145              Criciúma     Santa Catarina     214493
146      147           Passo Fundo  Rio Grande do Sul     206215
157      158            Rio Grande  Rio Grande do Sul     191900
159      160              Alvorada  Rio Grande do Sul     187315
163      164        Jaraguá do Sul     Santa Catarina     182660
164      165            Guarapuava             Paraná     182093
181      182                 Lages     Santa Catarina     164981
197      198             Araucária             Paraná     151666
199      200                Toledo             Paraná     150470
201      202    Fazenda Rio Grande             Paraná     148873
204      205             Paranaguá             Paraná     145829
211      212               Brusque     Santa Catarina     141385
213      214    Balneário Camboriú     Santa Catarina     139155
216      217           Campo Largo             Paraná     136327
217      218          Cachoeirinha  Rio Grande do Sul     136258
223      224     Santa Cruz do Sul  Rio Grande do Sul     133230
225      226       Sapucaia do Sul  Rio Grande do Sul     132107
230      231             Apucarana             Paraná     130134
236      237               Pinhais             Paraná     127019
247      248       Bento Gonçalves  Rio Grande do Sul     123151
252      253   Almirante Tamandaré             Paraná     119825
253      254             Arapongas             Paraná     119138
255      256             Piraquara             Paraná     118730
256      257               Sarandi             Paraná     118455
259      260                  Bagé  Rio Grande do Sul     117938
261      262            Uruguaiana  Rio Grande do Sul     117210
262      263              Umuarama             Paraná     117095
285      286               Tubarão     Santa Catarina     110088
289      290                 Cambé             Paraná     107208
294      295               Erechim  Rio Grande do Sul     105705
311      312              Camboriú     Santa Catarina     103074

In [36]:
df_populacao_sul=df_populacao_sul.reset_index(drop=True)
df_populacao_sul

    ranking             municipio                 uf  populacao
0         8              Curitiba             Paraná    1773718
1        11          Porto Alegre  Rio Grande do Sul    1332845
2        34             Joinville     Santa Catarina     616317
3        37              Londrina             Paraná     555965
4        39         Florianópolis     Santa Catarina     537211
5        48         Caxias do Sul  Rio Grande do Sul     463501
6        61               Maringá             Paraná     409657
7        71              Blumenau     Santa Catarina     361261
8        72          Ponta Grossa             Paraná     358371
9        78              Cascavel             Paraná     348051
10       79                Canoas  Rio Grande do Sul     347657
11       85  São José dos Pinhais             Paraná     329628
12       86               Pelotas  Rio Grande do Sul     325685
13       97         Foz do Iguaçu             Paraná     285415
14      103           Santa Maria  Rio Grande do Sul     271735
15      104              São José     Santa Catarina     270299
16      107              Gravataí  Rio Grande do Sul     265074
17      109                Itajaí     Santa Catarina     264054
18      114               Chapecó     Santa Catarina     254785
19      130               Colombo             Paraná     232212
20      134         Novo Hamburgo  Rio Grande do Sul     227646
21      140                Viamão  Rio Grande do Sul     224112
22      141               Palhoça     Santa Catarina     222598
23      144          São Leopoldo  Rio Grande do Sul     217409
24      145              Criciúma     Santa Catarina     214493
25      147           Passo Fundo  Rio Grande do Sul     206215
26      158            Rio Grande  Rio Grande do Sul     191900
27      160              Alvorada  Rio Grande do Sul     187315
28      164        Jaraguá do Sul     Santa Catarina     182660
29      165            Guarapuava             Paraná     182093
30      182                 Lages     Santa Catarina     164981
31      198             Araucária             Paraná     151666
32      200                Toledo             Paraná     150470
33      202    Fazenda Rio Grande             Paraná     148873
34      205             Paranaguá             Paraná     145829
35      212               Brusque     Santa Catarina     141385
36      214    Balneário Camboriú     Santa Catarina     139155
37      217           Campo Largo             Paraná     136327
38      218          Cachoeirinha  Rio Grande do Sul     136258
39      224     Santa Cruz do Sul  Rio Grande do Sul     133230
40      226       Sapucaia do Sul  Rio Grande do Sul     132107
41      231             Apucarana             Paraná     130134
42      237               Pinhais             Paraná     127019
43      248       Bento Gonçalves  Rio Grande do Sul     123151
44      253   Almirante Tamandaré             Paraná     119825
45      254             Arapongas             Paraná     119138
46      256             Piraquara             Paraná     118730
47      257               Sarandi             Paraná     118455
48      260                  Bagé  Rio Grande do Sul     117938
49      262            Uruguaiana  Rio Grande do Sul     117210
50      263              Umuarama             Paraná     117095
51      286               Tubarão     Santa Catarina     110088
52      290                 Cambé             Paraná     107208
53      295               Erechim  Rio Grande do Sul     105705
54      312              Camboriú     Santa Catarina     103074

In [37]:
df_populacao_sul.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ranking    55 non-null     int64
 1   municipio  55 non-null     object
 2   uf         55 non-null     object
 3   populacao  55 non-null     int64
dtypes: int64(2), object(2)
memory usage: 1.8+ KB

In [43]:
regiao_sul = ['Rio Grande do Sul', 'Santa Catarina', 'Paraná']
df_populacao_sul = df_populacao[(df_populacao['uf'].isin(regiao_sul)) & (df_populacao['populacao'] < 250000)]
df_populacao_sul

     ranking            municipio                 uf  populacao
129      130              Colombo             Paraná     232212
133      134        Novo Hamburgo  Rio Grande do Sul     227646
139      140               Viamão  Rio Grande do Sul     224112
140      141              Palhoça     Santa Catarina     222598
143      144         São Leopoldo  Rio Grande do Sul     217409
144      145             Criciúma     Santa Catarina     214493
146      147          Passo Fundo  Rio Grande do Sul     206215
157      158           Rio Grande  Rio Grande do Sul     191900
159      160             Alvorada  Rio Grande do Sul     187315
163      164       Jaraguá do Sul     Santa Catarina     182660
164      165           Guarapuava             Paraná     182093
181      182                Lages     Santa Catarina     164981
197      198            Araucária             Paraná     151666
199      200               Toledo             Paraná     150470
201      202   Fazenda Rio Grande             Paraná     148873
204      205            Paranaguá             Paraná     145829
211      212              Brusque     Santa Catarina     141385
213      214   Balneário Camboriú     Santa Catarina     139155
216      217          Campo Largo             Paraná     136327
217      218         Cachoeirinha  Rio Grande do Sul     136258
223      224    Santa Cruz do Sul  Rio Grande do Sul     133230
225      226      Sapucaia do Sul  Rio Grande do Sul     132107
230      231            Apucarana             Paraná     130134
236      237              Pinhais             Paraná     127019
247      248      Bento Gonçalves  Rio Grande do Sul     123151
252      253  Almirante Tamandaré             Paraná     119825
253      254            Arapongas             Paraná     119138
255      256            Piraquara             Paraná     118730
256      257              Sarandi             Paraná     118455
259      260                 Bagé  Rio Grande do Sul     117938
261      262           Uruguaiana  Rio Grande do Sul     117210
262      263             Umuarama             Paraná     117095
285      286              Tubarão     Santa Catarina     110088
289      290                Cambé             Paraná     107208
294      295              Erechim  Rio Grande do Sul     105705
311      312             Camboriú     Santa Catarina     103074

## Unindo Tabelas

In [44]:
dados_area_urbana=pd.read_csv('/content/drive/MyDrive/CURSOS/Estudos - Data Analitycs/Tic - Análise de dados com paython /Módulo 2/Aula 2/area_urbana.csv')
dados_area_urbana

     ranking       municipio                uf  area urbana km²
0          1       São Paulo         São Paulo         914.5644
1          2  Rio de Janeiro    Rio de Janeiro         640.3365
2          3        Brasília  Distrito Federal         590.2166
3          4        Curitiba            Paraná         336.5066
4          5         Goiânia             Goiás         301.5507
..       ...             ...               ...              ...
950      951         Ubajara             Ceará          10.0417
951      952        Palmeira            Paraná          10.0379
952      953         Pitanga            Paraná          10.0211
953      954  Nova Esperança            Paraná          10.0148
954      955       Ouro Fino      Minas Gerais          10.0131

[955 rows x 4 columns]

In [45]:
dados_area_urbana.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 955 entries, 0 to 954
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ranking          955 non-null    int64
 1   municipio        955 non-null    object
 2   uf               955 non-null    object
 3   area urbana km²  955 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 30.0+ KB

In [46]:
dados_area_urbana.head()

   ranking       municipio                uf  area urbana km²
0        1       São Paulo         São Paulo         914.5644
1        2  Rio de Janeiro    Rio de Janeiro         640.3365
2        3        Brasília  Distrito Federal         590.2166
3        4        Curitiba            Paraná         336.5066
4        5         Goiânia             Goiás         301.5507

In [51]:
#unindo os daframes
df_merged = pd.merge(
    left=df_populacao, right=dados_area_urbana,
    how='outer', on=['municipio','uf'],
    suffixes=['_populacao','_area_urbana']
)

In [53]:
df_merged.head()

,ranking_populacao,municipio,uf,populacao,ranking_area_urbana,area urbana km²
0,190.0,Abaetetuba,Pará,158188.0,336.0,26.1655
1,NaN,Abreu e Lima,Pernambuco,NaN,499.0,18.9961
2,NaN,Acaraú,Ceará,NaN,585.0,16.3326
3,NaN,Adamantina,São Paulo,NaN,769.0,12.4262
4,NaN,Agudo,Rio Grande do Sul,NaN,771.0,12.3981

In [54]:
df_merged.tail()

,ranking_populacao,municipio,uf,populacao,ranking_area_urbana,area urbana km²
952,NaN,Xinguara,Pará,NaN,584.0,16.3999
953,NaN,Zé Doca,Maranhão,NaN,844.0,11.3096
954,NaN,Água Boa,Mato Grosso,NaN,885.0,10.7856
955,137.0,Águas Lindas de Goiás,Goiás,225693.0,158.0,43.8678
956,NaN,Óbidos,Pará,NaN,770.0,12.4217

In [50]:
df_merged.info ()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 957 entries, 0 to 956
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ranking_populacao    319 non-null    float64
 1   municipio            957 non-null    object
 2   uf                   957 non-null    object
 3   populacao            319 non-null    float64
 4   ranking_area_urbana  955 non-null    float64
 5   area urbana km²      955 non-null    float64
dtypes: float64(4), object(2)
memory usage: 45.0+ KB

In [55]:
df_merged.isna().sum()

ranking_populacao      638
municipio                0
uf                       0
populacao              638
ranking_area_urbana      2
area urbana km²          2
dtype: int64

## Mantendo dados existentes nas duas tabelas

In [73]:
df_merge_inner = pd.merge(
    left=df_populacao, right=dados_area_urbana,
    how='inner', on=['municipio','uf'],
    suffixes=['_populacao','_area_urbana']
)
df_merge_inner.dropna(inplace=True)

In [70]:
df_merge_inner.head()

,ranking_populacao,municipio,uf,populacao,ranking_area_urbana,area urbana km²
0,1,São Paulo,São Paulo,11451999,1,914.5644
1,2,Rio de Janeiro,Rio de Janeiro,6211223,2,640.3365
2,3,Brasília,Distrito Federal,2817381,3,590.2166
3,4,Fortaleza,Ceará,2428708,8,253.6912
4,5,Salvador,Bahia,2417678,12,196.2572

In [74]:
df_merge_inner.tail()

,ranking_populacao,municipio,uf,populacao,ranking_area_urbana,area urbana km²
312,315,Manacapuru,Amazonas,101883,630,15.5020
313,316,Balsas,Maranhão,101767,324,26.9199
314,317,Lagarto,Sergipe,101579,314,27.2336
315,318,Assis,São Paulo,101409,320,27.0427
316,319,Itaperuna,Rio de Janeiro,101041,478,19.9217

In [75]:
df_merge_inner.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 317 entries, 0 to 316
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ranking_populacao    317 non-null    int64
 1   municipio            317 non-null    object
 2   uf                   317 non-null    object
 3   populacao            317 non-null    int64
 4   ranking_area_urbana  317 non-null    int64
 5   area urbana km²      317 non-null    float64
dtypes: float64(1), int64(3), object(2)
memory usage: 15.0+ KB

## Organizando e Savando o novo dataframe

In [77]:
df_merge_inner['habitante por km²']=df_merge_inner['populacao']/df_merge_inner['area urbana km²']
df_merge_inner

,ranking_populacao,municipio,uf,populacao,ranking_area_urbana,area urbana km²,habitante por km²
0,1,São Paulo,São Paulo,11451999,1,914.5644,12521.807103
1,2,Rio de Janeiro,Rio de Janeiro,6211223,2,640.3365,9699.935893
2,3,Brasília,Distrito Federal,2817381,3,590.2166,4773.469604
3,4,Fortaleza,Ceará,2428708,8,253.6912,9573.481461
4,5,Salvador,Bahia,2417678,12,196.2572,12318.926388
...,...,...,...,...,...,...,...
312,315,Manacapuru,Amazonas,101883,630,15.5020,6572.248742
313,316,Balsas,Maranhão,101767,324,26.9199,3780.363226
314,317,Lagarto,Sergipe,101579,314,27.2336,3729.914517
315,318,Assis,São Paulo,101409,320,27.0427,3749.958399
316,319,Itaperuna,Rio de Janeiro,101041,478,19.9217,5071.906514

In [81]:
df_merge_inner=df_merge_inner.sort_values(by='habitante por km²', ascending=False).reset_index(drop=True)
df_merge_inner

,ranking_populacao,municipio,uf,populacao,ranking_area_urbana,area urbana km²,habitante por km²
0,101,Taboão da Serra,São Paulo,273542,516,18.6092,14699.288524
1,63,Diadema,São Paulo,393237,311,27.5114,14293.601925
2,83,São Vicente,São Paulo,329911,334,26.2317,12576.805926
3,53,São João de Meriti,Rio de Janeiro,440962,221,35.2135,12522.526872
4,1,São Paulo,São Paulo,11451999,1,914.5644,12521.807103
...,...,...,...,...,...,...,...
312,188,Atibaia,São Paulo,158647,100,64.2782,2468.130719
313,139,Itaboraí,Rio de Janeiro,224267,52,92.8138,2416.310937
314,251,Itatiba,São Paulo,121590,130,52.2255,2328.173019
315,154,Maricá,Rio de Janeiro,197277,60,85.8766,2297.214841
316,232,Araruama,Rio de Janeiro,129671,96,64.8404,1999.848860

In [82]:
df_merge_inner['Ranking de Densidade']=df_merge_inner.index+1
df_merge_inner

,ranking_populacao,municipio,uf,populacao,ranking_area_urbana,area urbana km²,habitante por km²,Ranking de Densidade
0,101,Taboão da Serra,São Paulo,273542,516,18.6092,14699.288524,1
1,63,Diadema,São Paulo,393237,311,27.5114,14293.601925,2
2,83,São Vicente,São Paulo,329911,334,26.2317,12576.805926,3
3,53,São João de Meriti,Rio de Janeiro,440962,221,35.2135,12522.526872,4
4,1,São Paulo,São Paulo,11451999,1,914.5644,12521.807103,5
...,...,...,...,...,...,...,...,...
312,188,Atibaia,São Paulo,158647,100,64.2782,2468.130719,313
313,139,Itaboraí,Rio de Janeiro,224267,52,92.8138,2416.310937,314
314,251,Itatiba,São Paulo,121590,130,52.2255,2328.173019,315
315,154,Maricá,Rio de Janeiro,197277,60,85.8766,2297.214841,316
316,232,Araruama,Rio de Janeiro,129671,96,64.8404,1999.848860,317

In [85]:
df_merge_inner=df_merge_inner[
    ['municipio','uf',
     'populacao', 'ranking_populacao',
     'area urbana km²', 'ranking_area_urbana',
     'habitante por km²','Ranking de Densidade']
]
df_merge_inner

,municipio,uf,populacao,ranking_populacao,area urbana km²,ranking_area_urbana,habitante por km²,Ranking de Densidade
0,Taboão da Serra,São Paulo,273542,101,18.6092,516,14699.288524,1
1,Diadema,São Paulo,393237,63,27.5114,311,14293.601925,2
2,São Vicente,São Paulo,329911,83,26.2317,334,12576.805926,3
3,São João de Meriti,Rio de Janeiro,440962,53,35.2135,221,12522.526872,4
4,São Paulo,São Paulo,11451999,1,914.5644,1,12521.807103,5
...,...,...,...,...,...,...,...,...
312,Atibaia,São Paulo,158647,188,64.2782,100,2468.130719,313
313,Itaboraí,Rio de Janeiro,224267,139,92.8138,52,2416.310937,314
314,Itatiba,São Paulo,121590,251,52.2255,130,2328.173019,315
315,Maricá,Rio de Janeiro,197277,154,85.8766,60,2297.214841,316
316,Araruama,Rio de Janeiro,129671,232,64.8404,96,1999.848860,317

In [88]:
df_merge_inner.to_csv('/content/drive/MyDrive/CURSOS/Estudos - Data Analitycs/Tic - Análise de dados com paython /Módulo 2/Aula 2/dados_populacao_densidade.csv', index=False)