<a href="https://colab.research.google.com/github/alra-code/Portifolio_python/blob/main/An%C3%A1lise_de_dados_com_python_modulo_2_lendo_arquivos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Lendo arquivos csv e salvando no drive

In [8]:
#improtações
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
#abrindo o arquivo
df_dados_csv=pd.read_csv('/content/drive/MyDrive/CURSOS/Estudos - Data Analitycs/Tic - Análise de dados com paython /Módulo 2/cidades.csv')
df_dados_csv.head()

   ranking       municipio                uf   populacao
0        1       São Paulo         São Paulo  11 451 999
1        2  Rio de Janeiro    Rio de Janeiro   6 211 223
2        3        Brasília  Distrito Federal   2 817 381
3        4       Fortaleza             Ceará   2 428 708
4        5        Salvador             Bahia   2 417 678

In [5]:
#abrindo outro arquivo
df_dados_heach=pd.read_csv('/content/drive/MyDrive/CURSOS/Estudos - Data Analitycs/Tic - Análise de dados com paython /Módulo 2/cidades_separado_por_hashtag.csv', sep='#', header=None)
df_dados_heach.head()

         0               1                 2           3
0  ranking       municipio                uf   populacao
1        1       São Paulo         São Paulo  11 451 999
2        2  Rio de Janeiro    Rio de Janeiro   6 211 223
3        3        Brasília  Distrito Federal   2 817 381
4        4       Fortaleza             Ceará   2 428 708

In [11]:
#salvando o arquivo no drive
caminho_arquivo = '/content/drive/MyDrive/CURSOS/Estudos - Data Analitycs/Tic - Análise de dados com paython /Módulo 2/csv_salvo.csv'
df_dados_heach.to_csv(caminho_arquivo)

### Lendo arquivo excel e salvando no drive

In [16]:
#improtações
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [21]:
#abrindo o arquivo - para o python Populacao != populacao
df_populacao = pd.read_excel('/content/drive/MyDrive/CURSOS/Estudos - Data Analitycs/Tic - Análise de dados com paython /Módulo 2/cidades.xlsx', sheet_name='Populacao')
df_populacao.head()

   ranking       municipio                uf   populacao
0        1       São Paulo         São Paulo  11 451 999
1        2  Rio de Janeiro    Rio de Janeiro   6 211 223
2        3        Brasília  Distrito Federal   2 817 381
3        4       Fortaleza             Ceará   2 428 708
4        5        Salvador             Bahia   2 417 678

In [24]:
#gravando o arquivo. Evite espaços entre virgulas e texto
df_populacao.to_excel('/content/drive/MyDrive/CURSOS/Estudos - Data Analitycs/Tic - Análise de dados com paython /Módulo 2/populacao_salvo.xlsx',index=False)

## Lendo arquivo json e salvando no drive

In [26]:
#lendo o arquivo json
df_populacao_json = pd.read_json('/content/drive/MyDrive/CURSOS/Estudos - Data Analitycs/Tic - Análise de dados com paython /Módulo 2/cidades.json')
df_populacao_json.head()

   ranking       municipio                uf   populacao
0        1       São Paulo         São Paulo  11 451 999
1        2  Rio de Janeiro    Rio de Janeiro   6 211 223
2        3        Brasília  Distrito Federal   2 817 381
3        4       Fortaleza             Ceará   2 428 708
4        5        Salvador             Bahia   2 417 678

In [28]:
#salvando o arquivo e usando indet=4 para organizar
df_populacao_json.to_json('/content/drive/MyDrive/CURSOS/Estudos - Data Analitycs/Tic - Análise de dados com paython /Módulo 2/populacao_salvo.json', indent=4)

## Lendo arquivo xml e salvando no drive

In [30]:
#lendo o arquivo xml
df_populacao_xml = pd.read_xml('/content/drive/MyDrive/CURSOS/Estudos - Data Analitycs/Tic - Análise de dados com paython /Módulo 2/cidades.xml')
df_populacao_xml.head()

   ranking       municipio                uf   populacao
0        1       São Paulo         São Paulo  11 451 999
1        2  Rio de Janeiro    Rio de Janeiro   6 211 223
2        3        Brasília  Distrito Federal   2 817 381
3        4       Fortaleza             Ceará   2 428 708
4        5        Salvador             Bahia   2 417 678

In [32]:
#salvando o arquivo
df_populacao_xml.to_xml('/content/drive/MyDrive/CURSOS/Estudos - Data Analitycs/Tic - Análise de dados com paython /Módulo 2/populacao_salvo.xml',index=False)

## Lendo arquivo html e salvando no drive

In [37]:
#lendo o arquivo html
df_populacao_html = pd.read_html('/content/drive/MyDrive/CURSOS/Estudos - Data Analitycs/Tic - Análise de dados com paython /Módulo 2/cidades.html',encoding='utf-8')
df_populacao_html[0].head() #mostra somente os 5 primeiros resultados

   ranking       municipio                uf   populacao
0        1       São Paulo         São Paulo  11 451 999
1        2  Rio de Janeiro    Rio de Janeiro   6 211 223
2        3        Brasília  Distrito Federal   2 817 381
3        4       Fortaleza             Ceará   2 428 708
4        5        Salvador             Bahia   2 417 678

In [38]:
print(df_populacao_html[0]) # imprime o DataFrame completo.

     ranking       municipio                uf   populacao
0          1       São Paulo         São Paulo  11 451 999
1          2  Rio de Janeiro    Rio de Janeiro   6 211 223
2          3        Brasília  Distrito Federal   2 817 381
3          4       Fortaleza             Ceará   2 428 708
4          5        Salvador             Bahia   2 417 678
..       ...             ...               ...         ...
314      315      Manacapuru          Amazonas     101 883
315      316          Balsas          Maranhão     101 767
316      317         Lagarto           Sergipe     101 579
317      318           Assis         São Paulo     101 409
318      319       Itaperuna    Rio de Janeiro     101 041

[319 rows x 4 columns]

In [40]:
#salvando o arquivo
df_populacao_html[0].to_html('/content/drive/MyDrive/CURSOS/Estudos - Data Analitycs/Tic - Análise de dados com paython /Módulo 2/populacao_salvo.html')