<a href="https://colab.research.google.com/github/alra-code/Portifolio_python/blob/main/An%C3%A1lise_de_dados_com_python_modulo_2_Lidando_com_dados_faltantes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Lidando com dados faltantes com o Pandas

In [35]:
#importação da biblioteca
import pandas as pd

#carregando o arquivo do google drive
df_diabetes=pd.read_excel('/content/drive/MyDrive/CURSOS/Estudos - Data Analitycs/Tic - Análise de dados com paython /Módulo 2/Aula 3/diabetes.xlsx')

In [36]:
df_diabetes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   pressao arterial          733 non-null    float64
 1   concentraÃ§ao de glicose  763 non-null    float64
 2   insulina                  394 non-null    float64
 3   tipo sanguineo            723 non-null    object
 4   idade                     768 non-null    int64
 5   imc                       757 non-null    float64
 6   diabetico                 768 non-null    object
dtypes: float64(4), int64(1), object(2)
memory usage: 42.1+ KB

In [37]:
df_diabetes.isnull().sum() #conhecendo os dados faltantes

pressao arterial             35
concentraÃ§ao de glicose      5
insulina                    374
tipo sanguineo               45
idade                         0
imc                          11
diabetico                     0
dtype: int64

In [38]:
df_diabetes['diabetico'].value_counts()

diabetico
N    500
S    268
Name: count, dtype: int64

In [39]:
df_diabetes.head() #corrigindo titulo da coluna

,pressao arterial,concentraÃ§ao de glicose,insulina,tipo sanguineo,idade,imc,diabetico
0,72.0,148.0,NaN,A,50,33.6,S
1,66.0,85.0,NaN,O,31,26.6,N
2,64.0,183.0,NaN,A,32,23.3,S
3,66.0,89.0,94.0,A,21,28.1,N
4,40.0,137.0,168.0,O,33,43.1,S

In [40]:
#corrigindo a grafia do titulo da coluna
df_diabetes = df_diabetes.rename(columns={'concentraÃ§ao de glicose': 'concentração de glicose'})
df_diabetes.head()

,pressao arterial,concentração de glicose,insulina,tipo sanguineo,idade,imc,diabetico
0,72.0,148.0,NaN,A,50,33.6,S
1,66.0,85.0,NaN,O,31,26.6,N
2,64.0,183.0,NaN,A,32,23.3,S
3,66.0,89.0,94.0,A,21,28.1,N
4,40.0,137.0,168.0,O,33,43.1,S

In [41]:
df_diabetes = df_diabetes.rename(columns={'pressao arterial': 'pressão arterial'})
df_diabetes.head()

,pressão arterial,concentração de glicose,insulina,tipo sanguineo,idade,imc,diabetico
0,72.0,148.0,NaN,A,50,33.6,S
1,66.0,85.0,NaN,O,31,26.6,N
2,64.0,183.0,NaN,A,32,23.3,S
3,66.0,89.0,94.0,A,21,28.1,N
4,40.0,137.0,168.0,O,33,43.1,S

## Descartando linhas com valores faltantes

In [42]:
# por ter poucos dados achei melhor remover. cada coluna represneta menos de 1%
# Remove linhas com valores faltantes em 'concentração de glicose' ou 'imc'
df_diabetes.dropna(subset=['concentração de glicose', 'imc'], inplace=True)
df_diabetes

,pressão arterial,concentração de glicose,insulina,tipo sanguineo,idade,imc,diabetico
0,72.0,148.0,NaN,A,50,33.6,S
1,66.0,85.0,NaN,O,31,26.6,N
2,64.0,183.0,NaN,A,32,23.3,S
3,66.0,89.0,94.0,A,21,28.1,N
4,40.0,137.0,168.0,O,33,43.1,S
...,...,...,...,...,...,...,...
763,76.0,101.0,180.0,A,63,32.9,N
764,70.0,122.0,NaN,A,27,36.8,N
765,72.0,121.0,112.0,O,30,26.2,N
766,60.0,126.0,NaN,NaN,47,30.1,S
767,70.0,93.0,NaN,A,23,30.4,N

In [43]:
df_diabetes.isnull().sum()

pressão arterial            28
concentração de glicose      0
insulina                   360
tipo sanguineo              43
idade                        0
imc                          0
diabetico                    0
dtype: int64

In [44]:
df_diabetes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 752 entries, 0 to 767
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   pressão arterial         724 non-null    float64
 1   concentração de glicose  752 non-null    float64
 2   insulina                 392 non-null    float64
 3   tipo sanguineo           709 non-null    object
 4   idade                    752 non-null    int64
 5   imc                      752 non-null    float64
 6   diabetico                752 non-null    object
dtypes: float64(4), int64(1), object(2)
memory usage: 47.0+ KB

## Substituindo valores

In [45]:
df_diabetes.isna().sum()

pressão arterial            28
concentração de glicose      0
insulina                   360
tipo sanguineo              43
idade                        0
imc                          0
diabetico                    0
dtype: int64

In [46]:
df_diabetes[df_diabetes['insulina'].isna()].head(10)

,pressão arterial,concentração de glicose,insulina,tipo sanguineo,idade,imc,diabetico
0,72.0,148.0,NaN,A,50,33.6,S
1,66.0,85.0,NaN,O,31,26.6,N
2,64.0,183.0,NaN,A,32,23.3,S
5,74.0,116.0,NaN,A,30,25.6,N
7,NaN,115.0,NaN,A,29,35.3,N
10,92.0,110.0,NaN,O,30,37.6,N
11,74.0,168.0,NaN,NaN,34,38.0,S
12,80.0,139.0,NaN,O,57,27.1,N
15,NaN,100.0,NaN,AB,32,30.0,S
17,74.0,107.0,NaN,AB,31,29.6,S

In [47]:
#substituindo o valor para uma informação mais legivel
df_diabetes['leu insulina'] = ~df_diabetes['insulina'].isna()
df_diabetes.head()

,pressão arterial,concentração de glicose,insulina,tipo sanguineo,idade,imc,diabetico,leu insulina
0,72.0,148.0,NaN,A,50,33.6,S,False
1,66.0,85.0,NaN,O,31,26.6,N,False
2,64.0,183.0,NaN,A,32,23.3,S,False
3,66.0,89.0,94.0,A,21,28.1,N,True
4,40.0,137.0,168.0,O,33,43.1,S,True

In [48]:
#retirando a coluna com dados faltantes
df_diabetes.drop(columns='insulina', inplace=True)
df_diabetes.head()

,pressão arterial,concentração de glicose,tipo sanguineo,idade,imc,diabetico,leu insulina
0,72.0,148.0,A,50,33.6,S,False
1,66.0,85.0,O,31,26.6,N,False
2,64.0,183.0,A,32,23.3,S,False
3,66.0,89.0,A,21,28.1,N,True
4,40.0,137.0,O,33,43.1,S,True

In [50]:
#organizando o dataframe
df_diabetes=df_diabetes[[
    'pressão arterial',
    'concentração de glicose',
    'leu insulina', 'tipo sanguineo',
    'idade','imc', 'diabetico',
]]
df_diabetes

,pressão arterial,concentração de glicose,leu insulina,tipo sanguineo,idade,imc,diabetico
0,72.0,148.0,False,A,50,33.6,S
1,66.0,85.0,False,O,31,26.6,N
2,64.0,183.0,False,A,32,23.3,S
3,66.0,89.0,True,A,21,28.1,N
4,40.0,137.0,True,O,33,43.1,S
...,...,...,...,...,...,...,...
763,76.0,101.0,True,A,63,32.9,N
764,70.0,122.0,False,A,27,36.8,N
765,72.0,121.0,True,O,30,26.2,N
766,60.0,126.0,False,NaN,47,30.1,S
767,70.0,93.0,False,A,23,30.4,N

In [51]:
df_diabetes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 752 entries, 0 to 767
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   pressão arterial         724 non-null    float64
 1   concentração de glicose  752 non-null    float64
 2   leu insulina             752 non-null    bool
 3   tipo sanguineo           709 non-null    object
 4   idade                    752 non-null    int64
 5   imc                      752 non-null    float64
 6   diabetico                752 non-null    object
dtypes: bool(1), float64(3), int64(1), object(2)
memory usage: 41.9+ KB

## Preenchendo valores

In [52]:
df_diabetes.isna().sum()

pressão arterial           28
concentração de glicose     0
leu insulina                0
tipo sanguineo             43
idade                       0
imc                         0
diabetico                   0
dtype: int64

In [53]:
df_diabetes['pressão arterial']

0      72.0
1      66.0
2      64.0
3      66.0
4      40.0
       ...
763    76.0
764    70.0
765    72.0
766    60.0
767    70.0
Name: pressão arterial, Length: 752, dtype: float64

In [54]:

df_diabetes['tipo sanguineo']

0        A
1        O
2        A
3        A
4        O
      ...
763      A
764      A
765      O
766    NaN
767      A
Name: tipo sanguineo, Length: 752, dtype: object

In [55]:
#analisando a coluna com dados
df_diabetes['pressão arterial'].describe()

count    724.000000
mean      72.400552
std       12.379870
min       24.000000
25%       64.000000
50%       72.000000
75%       80.000000
max      122.000000
Name: pressão arterial, dtype: float64

In [56]:
#analisando a coluna
df_diabetes['tipo sanguineo'].value_counts()

tipo sanguineo
A     390
O     223
B      75
AB     21
Name: count, dtype: int64

In [59]:
#substituindo os campos vazios por informações mais uteis. Como a média e valor comum
df_diabetes.fillna({'pressão arterial': 72.4, 'tipo sanguineo':'A'}, inplace=True)
df_diabetes.info ()

<class 'pandas.core.frame.DataFrame'>
Index: 752 entries, 0 to 767
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   pressão arterial         752 non-null    float64
 1   concentração de glicose  752 non-null    float64
 2   leu insulina             752 non-null    bool
 3   tipo sanguineo           752 non-null    object
 4   idade                    752 non-null    int64
 5   imc                      752 non-null    float64
 6   diabetico                752 non-null    object
dtypes: bool(1), float64(3), int64(1), object(2)
memory usage: 41.9+ KB

In [60]:
df_diabetes.isnull().sum()

pressão arterial           0
concentração de glicose    0
leu insulina               0
tipo sanguineo             0
idade                      0
imc                        0
diabetico                  0
dtype: int64

### Nesse exercício pude conhecer os dados para trata-los corretamente, e limpa-los e organiza-los para iniciar uma análise mais efetiva.